### PR TITLE
chore: update cached stats inside PollExecution

### PR DESCRIPTION
**Pull request by romange**

### CODE REVIEW

**Review by dranikpg — APPROVED** [review]
would be helpful if you left a comment why we have to update them only when we progressed on the txq, but not on ooo

**Comment by romange** [comment]
it's actually a mishup on my end

**Comment by romange** [comment]
why approving then? 😆

**Comment by dranikpg** [comment]
Oh, have you though about the fact that we don't run PollExecution if `CanRunInlined` is true in ScheduleInternal? So for single hop commands on a single thread, we'll never run it 😵

**Comment by romange** [comment]
I did not but this PR is a strict improvement over the previous case where we had only a periodic fiber, and it covers vast majority of cases. There is no hard requirement to cover CacheStats for ALL cases.

**Review by dranikpg — APPROVED** [review]
Ok, maybe I ddin't understand the motivation, but looks fine

**Pull request merged**
