### PR TITLE
chore: fix cluster replication test

### PR DESCRIPTION
**Pull request by dranikpg**

### CODE REVIEW

**Comment by BorysTheDev** [comment]
@dranikpg The test is skipped

**Comment by BorysTheDev** [comment]
looks OK, but before merge please run at least 100 times per release and debug build, because it was really unstable

**Review by BorysTheDev — APPROVED** [review]

**Comment by dranikpg** [comment]
image

**Comment by romange** [comment]
@adiholden  @chakaz  should we close this PR?

**Comment by BorysTheDev** [comment]
@romange I've already fixed it and merged

**Pull request closed without merging**
