### PR TITLE
fix(bug): dashtable split crashes when moving items from the old segment

### PR DESCRIPTION
**Pull request by romange**
Segment's Insert function uses an opportunistic heuristic that chose a bucket with smaller items among two available. This creates a problem with split that goes from a smaller bucket to the biggest one and moves items to the new segment. In rare case, the heurstic fills up a the next bucket with items that could reside in earlier buckets and then that bucket does not have space for its own items. Eventually, items that had enough space in the old segment do not find space in the new one

The fix is to adopt a conservative approach during split and try to use a home bucket first. Home bucket is usually a smaller one. This approach should be optimal because Split starts with smaller buckets first (can be proven iteratively).

Signed-off-by: Roman Gershman <roman@dragonflydb.io>

### CODE REVIEW

**Comment by dranikpg** [comment]
The test I sent you is only 826/840 on segment capacity. What if we fill a segment fully in such a way, that spread does not decrease but increase the capacity. We'd have BUCKET_SIZE + 1 entries with the same bucket hash, but one of them is in the neighbour bucket.

So lets number the buckets A B C D and elements with hashes a b c d (after their home bucket). Lets say the bucket capacity is 3.

You insert b b b c c c c c c c and get
A: b (b is here because of spread)
B: b b c
C: c c c
D: c c c 

Now you insert them in order and you get:
A: 
B: b b b
C: c c c
D: c c c

And one more c nowhere to put. Or am I missing something?

**Comment by romange** [comment]
An element can reside in home bucket i or i+1 mod n, thus b can not reside
in bucket A

**Comment by dranikpg** [comment]
Oh, for some reason I thought spread checks the preceding bucket and not the following... In this case you inductive logic should be correct

**Review by dranikpg — APPROVED** [review]

**Comment by romange** [comment]
Yeah, DenseSet spreads into both directions but not DashTable.

**Pull request merged**
