### PR TITLE
fix(server): exit gracefully when iouring not supported

### PR DESCRIPTION
**Pull request by iko1**
Signed-off-by: iko1 <me@remotecpp.dev>

### CODE REVIEW

**Review by romange — APPROVED** [review]

**Review by romange — CHANGES_REQUESTED** [review]
Please free uring in case it's supported.

**Comment by iko1** [comment]
> Please free uring in case it's supported.

The `io_uring_queue_init_params `call exits with EFAULT  error code on the supported system, because invalid arguments are supplied to the function, so no need to release any resources.

**Comment by iko1** [comment]
> Please free uring in case it's supported.

I think no need to release resources here.
The `io_uring_queue_init_params(0, nullptr, nullptr)` call always returns an error result even on supported system.
On a supported system, the error result is BAD ADDRESS because `struct io_uring *ring` parameter is `nullptr`.

**Comment by romange** [comment]
All right, smarty-pants. LGTM.

**Comment by romange** [comment]
Resolves #169

**Pull request merged**
