### PR TITLE
CI: Use v3 of Actions "upload-artifacts", "checkout" and "cache"

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates the GitHub Actions to latest major tags.

### CODE REVIEW

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
Thanks!

**Comment by olleolleolle** [comment]
@romange Oh, this PR should not be merged before all the Workflows are using those v3 versions.

**Comment by romange** [comment]
what do you mean? what will happen if we merge?

**Comment by olleolleolle** [comment]
@romange I just wanted to not leave details behind!

**Comment by olleolleolle** [comment]
@romange I force-pushed a change, which now includes all the changes I wanted to have in the first one.

**Pull request merged**
