### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Comment by romange** [comment]
@ryanrussell no job security for you.

**Comment by romange** [comment]
Thanks Cui.

**Comment by romange** [comment]
@cuishuang  if you do not mind, can you please use "git commit -s --amend" and force push it?

**Comment by cuishuang** [comment]
> @cuishuang if you do not mind, can you please use "git commit -s --amend" and force push it?

Of course. Done

**Review by romange — APPROVED** [review]

**Pull request merged**
