### PR TITLE
Feat(Helm chart): Add env vars into pods

### PR DESCRIPTION
**Pull request by andreibe24**
The current change is required to allow use of [S3 bucket backups](https://www.dragonflydb.io/docs/managing-dragonfly/backups#authentication).

### CODE REVIEW

**Comment by chakaz** [comment]
@Pothulapati would it be at all possible for you to take a look? :pray:

**Review by Pothulapati — CHANGES_REQUESTED** [review]
Mostly loooks right. 

Can you add a example/test-case in a new values file under the /contrib/charts/dragonfly/ci', run go test ./... --update` and make sure the output is what we expect and won't break with other changes in the future?

Thanks

**Comment by andreibe24** [comment]
Hi @Pothulapati,
I've posted the CI helm tests.

Yours,
Andrei B

**Review by romange — APPROVED** [review]

**Review by Pothulapati — APPROVED** [review]
LGTM

**Pull request merged**
