### PR TITLE
feat(helm) - Enable configuring service type LoadBalancer with a Static IP

### PR DESCRIPTION
**Pull request by mutiadavid**
Enable configuring service type LoadBalancer with a Static IP.

This is very helpful when using cloud providers such as Azure Kubernetes Service (AKS) and you want to assign a static IP to the dragonfly service.

### CODE REVIEW

**Comment by Pothulapati** [comment]
@mutiadavid Thanks for raising the change and its a valid one. Can you make the following changes so that we can merge this?
- Rebase the branch
- And add a test that verifies the behaviour? This is very simple and you can follow the [doc](https://github.com/dragonflydb/dragonfly/blob/main/CONTRIBUTING.md#rendering-helm-golden-files) and [samples](https://github.com/dragonflydb/dragonfly/tree/main/contrib/charts/dragonfly/ci)

**Comment by mutiadavid** [comment]
@Pothulapati 
I have added the tests.  

Please let me know whether the merge from main the repository added is what you meant by rebase. 

Thanks.

**Comment by romange** [comment]
@mutiadavid  this PR fails our unit tests.

**Comment by romange** [comment]
@Pothulapati  it's possible that our tests are broken due to recent changes with TLS. You must pass `--requirepass` to dragonfly when using tls

**Comment by mutiadavid** [comment]
@romange @Pothulapati 
The file 'tls-values.golden.yaml' keeps on updating every time I run 'go test -v ./... -update' command. Does it have anything to do with the tests failing?

Changes to that file haven't been committed to the repo. 

image

**Comment by Pothulapati** [comment]
@mutiadavid I'm trying to fix the issue in CI with https://github.com/dragonflydb/dragonfly/pull/1696, Will update you once its merged, for you to rebase.

**Comment by Pothulapati** [comment]
@mutiadavid Fix just got merged: https://github.com/dragonflydb/dragonfly/pull/1696. Can you rebase your branch? 

Thanks!

**Comment by mutiadavid** [comment]
@Pothulapati I've merged the updates from main.

Thanks for fixing the issue.

**Review by Pothulapati — APPROVED** [review]
LGTM! Thanks for the contribution @mutiadavid

**Pull request merged**
