### PR TITLE
bug(helm) Fix tolerations and affinity mishandling in Helm template

### PR DESCRIPTION
**Pull request by kbelokon**
Hello,

This pull request addresses a significant issue found in the Helm template for Dragonfly deployment related to the mishandling of 'tolerations' and 'affinity'.

**Problem**:
The problem was that the Helm template incorrectly concatenated values within 'tolerations' and 'affinity', which led to erroneous YAML outputs. Specifically, the rendered YAML for the tolerations would incorrectly join the last toleration and 'affinity', as evidenced by the resulting YAML.

**Change**:
The change primarily involves updating the Helm chart's handling of 'tolerations', 'nodeSelector', and 'affinity' values. The adjustment lies in the removal of the dash (-) in the 'with' statement for each of the three values. The changes are as follows:

```yaml
# Before
{{- with .Values.tolerations -}}
{{- with .Values.nodeSelector -}}
{{- with .Values.affinity -}}

# After
{{- with .Values.tolerations }}
{{- with .Values.nodeSelector }}
{{- with .Values.affinity }}
```

With the proposed changes, the issue with the incorrect concatenation of values in 'tolerations' and 'affinity' is resolved. The generated YAML now correctly separates each section, ensuring the successful application of the Helm chart.

I have provided the changes in values for testing:

```yaml
tolerations:
  - key: key/high-memory
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  - key: key/high-memory
    operator: "Equal"
    value: "true"
    effect: "PreferNoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: key/node-kind
              operator: In
              values:
                - high-memory
```

Here is an example of how the previous code used to parse the values:
```yaml
tolerations:
  - effect: NoSchedule
    key: key/high-memory
    operator: Equal
    value: "true"
  - effect: PreferNoSchedule
    key: key/high-memory
    operator: Equal
    value: "true"affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: key/node-kind
          operator: In
          values:
          - high-memory
```

Please consider merging this fix as it greatly improves the usability and robustness of the Dragonfly deployment Helm chart.

### CODE REVIEW

**Comment by Pothulapati** [comment]
Hey @kbelokon, Sorry for the late reply. We had a CI issue to fix. Now, It's green!

So, The change looks good. Thanks for working on it. Would you mind adding a test with the values you mentioned in the issue into the golden tests folder, along with an empty golden output file? https://github.com/dragonflydb/dragonfly/tree/main/contrib/charts/dragonfly/ci

Once you do this, Run the commands from https://github.com/dragonflydb/dragonfly/blob/main/CONTRIBUTING.md#rendering-helm-golden-files, and it should automatically add the rendered output. With this, We will have a way to know if the output changes in the future.

Thanks. :)

**Review by Pothulapati — APPROVED** [review]
Thanks for raising the PR @kbelokon! I added the tests! :)

**Comment by kbelokon** [comment]
I just saw the changes you made to the PR and your earlier message. Apologies for not catching that sooner - your message slipped through my notifications.

Thanks for making those adjustments!

**Comment by Pothulapati** [comment]
@kbelokon Not at all. Thank YOU for taking out the time to contribute, and helping make the project better! :)

**Pull request merged**
