### PR TITLE
chore: pull helio and add ipv6 replication test

### PR DESCRIPTION
**Pull request by dranikpg**
Test that ipv6 replication really works

### CODE REVIEW

**Comment by romange** [comment]
seems that you found another bug:
https://github.com/dragonflydb/dragonfly/actions/runs/8646494546/job/23705942165?pr=2889#step:12:1064

**Comment by dranikpg** [comment]
image

**Comment by dranikpg** [comment]
image

**Comment by romange** [comment]
Seems that you are very close. Do not loose hope!

**Review by romange — APPROVED** [review]

**Pull request merged**
