### PR TITLE
ci: added clang pre-commit hook

### PR DESCRIPTION
**Pull request by lsvmello**
Signed-off-by: Leonardo Mello <lsvmello@gmail.com>

Closes https://github.com/dragonflydb/dragonfly/issues/200

- Added `clang-format` in `.pre-commit-config.yaml`
- Updated `CONTRIBUTING.md` with  `pre-commit` and `clang-format` installation script 

I ran `pre-commit run --all-files` but it change more than 100 files, so I didn't commit that change.
The `pre-commit` runs only on staged files, so the fixes can be done incrementally.

### CODE REVIEW

**Comment by romange** [comment]
Thanks, Leonardo. Do you know if it applies to PR checks as well?

**Comment by lsvmello** [comment]
It seems to have an integration with Github Actions: https://pre-commit.ci/
It is able to run the pre-commit and create a commit with the changes, but I think it might pollute the commit history.
Is that ok? the auto fix commits? Or the idea was just to notify that there is a problem on the commit so the developer can fix it?

**Comment by romange** [comment]
Yes, it should be part of pr checks that fail if format differs from the
submitted code.

**Comment by lsvmello** [comment]
@romange I've manage to add the CI Action to use the pre-commit run check and it fails if there is any error.

The problem is that I could make it work only with the `--all-files` flag, this runs for all files on the project and currently there are some files with no trailing ends and other problems, this could be easy fixed running `pre-commit run --all-files` locally and committing the changes, but there will be a lot of file changes.

The ideal scenario was to run the pre-commit only for changed files, for that the pre-commit program has the `--from-ref` and `--to-ref` parameters that it uses to transpile to `git diff` command. The problem is that I couldn't find the correct environment variables to use with these parameters.
For example, I tried to use it like `--from-ref $GITHUB_BASE_REF --to-ref $GITHUB_HEAD_REF` but this was transpiled to `git diff --name-only --no-ext-diff -z main..main` because my branch is also called `main`.

Does anyone has an idea on what might be the correct set o enviroment variables I  could use?
Or should we just use the `--all-files` flag instead?

**Review by romange — APPROVED** [review]

**Pull request merged**
