### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by omahs**
fix: typos

### CODE REVIEW

**Review by chakaz — APPROVED** [review]
Thanks for helping improving our documentation!

**Comment by chakaz** [comment]
@omahs looks like there are some line break changes that must be reformatted following your fixes, can you please follow up on the failure here?
https://github.com/dragonflydb/dragonfly/actions/runs/6392855728/job/17351018541?pr=1986
Thanks!

**Comment by omahs** [comment]
hey @chakaz it should be good now

**Review by chakaz — APPROVED** [review]
Thanks again, you rock!

**Pull request merged**
