### PR TITLE
feat(core): Support RISCV RVV

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Review by romange — COMMENTED** [review]
this file is not in helio

**Comment by howjmay** [comment]
I just opened a PR there

**Comment by romange** [comment]
Please rebase and sign the commit @howjmay

**Comment by howjmay** [comment]
done!

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
Thanks!

**Comment by howjmay** [comment]
Thank you too!

**Pull request merged**
