### PR TITLE
test: Run slow tests in regression runs (again:)

### PR DESCRIPTION
**Pull request by chakaz**

### CODE REVIEW

**Comment by romange** [comment]
@chakaz  maybe add a comment what this filter means (in your next pr). Also, I would like us to have a safeguard that checks we run "enough" tests and we did not disable a bunch of them  by mistake. Do not know how to do it though @kostasrim @chakaz  ideas are welcomed.

**Comment by chakaz** [comment]
I added a comment in https://github.com/dragonflydb/dragonfly/pull/2623
Not sure how to test your other (good) idea though :)

**Comment by kostasrim** [comment]
@chakaz @romange 

I got an idea for the safeguard. Look here: https://github.com/dragonflydb/dragonfly/pull/2547/files#diff-84a1dffad3636502d8db6b1e152f90fe0ab18249563aaba59862894f3cf8cb12R64

specifically look for `--duration`. It prints the `n` slowest tests. We can use that also as an assertion right? If the output contains let's say 20 or 30 or `n` we are good. It's a slight hijacking on the logic but it will work smoothly ;)

**Comment by romange** [comment]
it's good. can it output total number of tests? maybe add a safeguard with some margin on the overall test count?

**Comment by kostasrim** [comment]
> it's good. can it output total number of tests? 

It will output the `n` slowest tests. But if for example you wan't to assert that we run at least 10. Then `durations=10` will do exactly that. Furthermore, if you got `n` tests in total and you do `durations=n` you get back all the tests in a list ranked by the slowest to the fastest. So yes we can do whatever we want with it :stuck_out_tongue: 

>  maybe add a safeguard with some margin on the overall test count? 
yes we can postprocess the pytest output easily. Also we get the `n` slowest tests (which is a helpful info)

**Comment by romange** [comment]
I would separate between slowest tests info and safeguards on number of tests.
https://github.com/pytest-dev/pytest/pull/4673/files  shows we can grep number of "selected" tests and I think we should guard on total number

**Pull request merged**
