### PR TITLE
feat(docker-release): Support Alpine prod release

### PR DESCRIPTION
**Pull request by Pothulapati**
Follow up to https://github.com/dragonflydb/dragonfly/pull/1430

We should be building and publishing the alpine image of Dragonfly too like we already do with weekly releases.

Also, Need to test if the prod Dockerfile works as expected.

### CODE REVIEW

**Comment by romange** [comment]
Should we close this @Pothulapati  ?

**Comment by Pothulapati** [comment]
Closing this as I'm not sure if its needed! We can get back when we need an alpine release! (or someone asks for it)

**Comment by Hazmi35** [comment]
Hi. Is there a reason why there's no Alpine-based images for prod yet?

**Comment by romange** [comment]
@Hazmi35  we have not got a memo.

**Comment by Hazmi35** [comment]
> @Hazmi35 we have not got a memo.

I'm sorry what does that mean? It would be really nice if dragonfly officially provides Alpine-based container images as from what I've seen there's already the [Dockerfile for it](https://github.com/dragonflydb/dragonfly/blob/main/tools/packaging/Dockerfile.alpine-dev), albeit it's not published as an image officially. It would cut down the container image size, just like how Redis does.

**Pull request closed without merging**
