### PR TITLE
fix(server): Fix snapshot saving bug

### LINKED ISSUE #475: crash in SAVE command
reproduces consistently - I run dragonfly like this:
`./dragonfly --alsologtostderr --dir /mnt/vol1`

```
I20221110 15:18:49.225962 19740 init.cc:58] ./dragonfly running in debug mode.
I20221110 15:18:49.226240 19740 dfly_main.cc:271] Starting dragonfly df-dev-0000000
I20221110 15:18:49.226301 19740 dfly_main.cc:294] maxmemory has not been specified. Deciding myself....
I20221110 15:18:49.226423 19740 dfly_main.cc:299] Found 122.82GiB available memory. Setting maxmemory to 98.26GiB
I20221110 15:18:49.261417 19741 proactor.cc:418] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20221110 15:18:49.301544 19740 proactor_pool.cc:66] Running 16 io threads
I20221110 15:18:49.306895 19740 server_family.cc:380] Data directory is "/mnt/vol1"
I20221110 15:18:49.306999 19740 server_family.cc:128] Checking "/mnt/vol1/dump"
I20221110 15:18:49.307245 19743 listener_interface.cc:87] sock[52] AcceptServer - listening on port 6379
/home/dev/projects/dragonfly/src/server/server_family.cc:242:64: runtime error: member call on null pointer of type 'struct LinuxWriteWrapper'
    #0 0xaaaad75d62d4 in Close /home/dev/projects/dragonfly/src/server/server_family.cc:242
    #1 0xaaaad75e3318 in operator() /home/dev/projects/dragonfly/src/server/server_family.cc:858
    #2 0xaaaad761421c in __invoke_impl<void, dfly::ServerFamily::DoSave(bool, dfly::Transaction*, std::string*)::<lambda(unsigned int)>&, unsigned int> /usr/include/c++/11/bits/invoke.h:61
    #3 0xaaaad760ce5c in __invoke_r<void, dfly::ServerFamily::DoSave(bool, dfly::Transaction*, std::string*)::<lambda(unsigned int)>&, unsigned int> /usr/include/c++/11/bits/invoke.h:111
    #4 0xaaaad76057c4 in _M_invoke /usr/include/c++/11/bits/std_function.h:290
    #5 0xaaaad766bd30 in std::function<void (unsigned int)>::operator()(unsigned int) const /usr/include/c++/11/bits/std_function.h:590
    #6 0xaaaad75e2770 in RunStage /home/dev/projects/dragonfly/src/server/server_family.cc:783
    #7 0xaaaad75e4f38 in dfly::ServerFamily::DoSave(bool, dfly::Transaction*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /home/dev/projects/dragonfly/src/server/server_family.cc:923
    #8 0xaaaad75eb05c in dfly::ServerFamily::Save(absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) /home/dev/projects/dragonfly/src/server/server_family.cc:1119
    #9 0xaaaad75d37bc in operator() /home/dev/projects/dragonfly/src/server/server_family.cc:83
    #10 0xaaaad7627558 in invoke<const dfly::(anonymous namespace)::HandlerFunc(dfly::ServerFamily*, dfly::(anonymous namespace)::EngineFunc)::<lambda(facade::CmdArgList, dfly::ConnectionContext*)>&, absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*> /home/dev/projects/dragonfly/helio/base/function2.hpp:184
    #11 0xaaaad761efa4 in invoke /home/dev/projects/dragonfly/helio/base/function2.hpp:587
    #12 0xaaaad7416d60 in decltype(auto) fu2::abi_400::detail::type_erasure::tables::vtable<fu2::abi_400::detail::property<false, false, void (absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const> >::invoke<0ul, fu2::abi_400::detail::type_erasure::data_accessor const*, unsigned long const&, absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*>(fu2::abi_400::detail::type_erasure::data_accessor const*&&, unsigned long const&, absl::lts_20220623::Span<absl::lts_20220623::Span<char> >&&, dfly::ConnectionContext*&&) const /home/dev/projects/dragonfly/helio/base/function2.hpp:995
    #13 0xaaaad7416fd0 in decltype(auto) fu2::abi_400::detail::type_erasure::erasure<true, fu2::abi_400::detail::config<true, true, fu2::capacity_default>, fu2::abi_400::detail::property<false, false, void (absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const> >::invoke<0ul, fu2::abi_400::detail::type_erasure::erasure<true, fu2::abi_400::detail::config<true, true, fu2::capacity_default>, fu2::abi_400::detail::property<false, false, void (absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const> > const&, absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*>(fu2::abi_400::detail::type_erasure::erasure<true, fu2::abi_400::detail::config<true, true, fu2::capacity_default>, fu2::abi_400::detail::property<false, false, void (absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const> > const&, absl::lts_20220623::Span<absl::lts_20220623::Span<char> >&&, dfly::ConnectionContext*&&) /home/dev/projects/dragonfly/helio/base/function2.hpp:1213
    #14 0xaaaad74170cc in fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<0ul, fu2::abi_400::detail::function<fu2::abi_400::detail::config<true, true, fu2::capacity_default>, fu2::abi_400::detail::property<false, false, void (absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const> >, void (absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const>::operator()(absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const /home/dev/projects/dragonfly/helio/base/function2.hpp:775
    #15 0xaaaad740b3e0 in dfly::CommandId::Invoke(absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, dfly::ConnectionContext*) const /home/dev/projects/dragonfly/src/server/command_registry.h:112
    #16 0xaaaad739b1ac in dfly::Service::DispatchCommand(absl::lts_20220623::Span<absl::lts_20220623::Span<char> >, facade::ConnectionContext*) /home/dev/projects/dragonfly/src/server/main_service.cc:689
    #17 0xaaaad8021e70 in facade::Connection::ParseRedis() /home/dev/projects/dragonfly/src/facade/dragonfly_connection.cc:501
    #18 0xaaaad801e5bc in facade::Connection::ConnectionFlow(util::FiberSocketBase*) /home/dev/projects/dragonfly/src/facade/dragonfly_connection.cc:415
    #19 0xaaaad801ae54 in facade::Connection::HandleRequests() /home/dev/projects/dragonfly/src/facade/dragonfly_connection.cc:323
    #20 0xaaaad82f64d4 in util::ListenerInterface::RunSingleConnection(util::Connection*) /home/dev/projects/dragonfly/helio/util/listener_interface.cc:170
    #21 0xaaaad82f1d8c in operator() /home/dev/projects/dragonfly/helio/util/listener_interface.cc:117
    #22 0xaaaad830ab20 in __invoke_impl<void, util::ListenerInterface::RunAcceptLoop()::<lambda()> > /usr/include/c++/11/bits/invoke.h:61
    #23 0xaaaad8307200 in __invoke<util::ListenerInterface::RunAcceptLoop()::<lambda()> > /usr/include/c++/11/bits/invoke.h:96
    #24 0xaaaad8303f6c in __apply_impl<util::ListenerInterface::RunAcceptLoop()::<lambda()>, std::tuple<> > /usr/include/c++/11/tuple:1858
    #25 0xaaaad8303ff8 in apply<util::ListenerInterface::RunAcceptLoop()::<lambda()>, std::tuple<> > /usr/include/c++/11/tuple:1869
    #26 0xaaaad8304248 in run_ /usr/include/boost/fiber/context.hpp:434
    #27 0xaaaad83176a8 in __invoke_impl<boost::context::fiber, boost::context::fiber (boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >::*&)(boost::context::fiber&&), boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >*&, boost::context::fiber> /usr/include/c++/11/bits/invoke.h:74
    #28 0xaaaad83168d8 in __invoke<boost::context::fiber (boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >::*&)(boost::context::fiber&&), boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >*&, boost::context::fiber> /usr/include/c++/11/bits/invoke.h:97
    #29 0xaaaad8316220 in __call<boost::context::fiber, boost::context::fiber&&, 0, 1> /usr/include/c++/11/functional:422
    #30 0xaaaad831562c in operator()<boost::context::fiber> /usr/include/c++/11/functional:505
    #31 0xaaaad8314518 in __invoke_impl<boost::context::fiber, std::_Bind<boost::context::fiber (boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >::*(boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >*, std::_Placeholder<1>))(boost::context::fiber&&)>&, boost::context::fiber> /usr/include/c++/11/bits/invoke.h:61
    #32 0xaaaad83126cc in __invoke<std::_Bind<boost::context::fiber (boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >::*(boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >*, std::_Placeholder<1>))(boost::context::fiber&&)>&, boost::context::fiber> /usr/include/c++/11/bits/invoke.h:97
    #33 0xaaaad83110e8 in invoke<std::_Bind<boost::context::fiber (boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >::*(boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >*, std::_Placeholder<1>))(boost::context::fiber&&)>&, boost::context::fiber> /usr/include/c++/11/functional:98
    #34 0xaaaad830d398 in run /usr/include/boost/context/fiber_fcontext.hpp:143
    #35 0xaaaad830b324 in fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, std::_Bind<boost::context::fiber (boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >::*(boost::fibers::worker_context<util::ListenerInterface::RunAcceptLoop()::<lambda()> >*, std::_Placeholder<1>))(boost::context::fiber&&)> > > /usr/include/boost/context/fiber_fcontext.hpp:80
    #36 0xffff8c480d68 in make_fcontext (/lib/aarch64-linux-gnu/libboost_context.so.1.74.0+0xd68)

```

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #475 

I've added auto snapshot destruction in case of errors for the new multi-file snapshot feature, but didn't do it for the rdb files.

### CODE REVIEW

**Comment by dranikpg** [comment]
By the way, if we already review this part of code. 

In case of an error the other snapshots continue running. This is because we have no cancellation and we can't forecully stop them rn. Once we have cancellation for replication, we can use it here as well. If a single shard file fails, we should stop the whole process.

**Comment by romange** [comment]
Can you tell why timing matters? Why it works on other systems?

**Comment by romange** [comment]
Also - it does not even build 🤷‍♂️

**Comment by dranikpg** [comment]
Nothing to do with other systems, in the environment you gave me the target directory is not writable. 

In this case we call `Close()` on a linux file that didn't open in write mode. It doesn't happen with SAVE DF because it resets the snapshot in case of an erorr during initialization, so that no cleanup is peroformed

**Review by romange — APPROVED** [review]

**Pull request merged**
