### PR TITLE
feat(server): Add HTTL command

### LINKED ISSUE #3026: HTTL: access expiration time of hashes
**Is your feature request related to a problem? Please describe.**
I'm trying to access the expiration time of a hash created using `HSETEX`, but no such command exists.

**Describe the solution you'd like**
`HTTL key field` which behaves like `TTL key` but for hashes.

**Describe alternatives you've considered**
Tracking expiration time in an extra hash, but that just wastes storage for redundant information that already exists.

**Related**
#687 which originally added `HSETEX`

### PR DESCRIPTION
**Pull request by AyoubKaz07**
Access the expiration time of a hash created using ```HSETEX```
Format is like this: ```HTTL key field``` which behaves like TTL key but for hashes.

Fixes #3026

### CODE REVIEW

**Comment by romange** [comment]
@AyoubKaz07 thank you for submitting this PR! When I was reviewing it, I noticed we have already implemented a similar, `fieldttl` command that applies for both hashmaps and sets. We forgot to document it and it totally slipped my mind. Seems that HTTL duplicates the logic around this command. I believe if we document fieldttl we won't need HTTL anymore.

**Comment by AyoubKaz07** [comment]
Noticed it too, i thought there was a reason why it wasn't documented and required another HTTL command.

**Comment by AyoubKaz07** [comment]
Would love to take part and document `fieldttl` command, if you could point out where do i start

**Comment by romange** [comment]
Sure, our docs are here: https://github.com/dragonflydb/documentation

`fieldttl` should be under https://github.com/dragonflydb/documentation/tree/main/docs/command-reference/generic 
but I would also mention it in `setex` and `hsetex` pages.

**Pull request closed without merging**
