### PR TITLE
Add store test case for GeoRadiusByMember

### PR DESCRIPTION
**Pull request by azuredream**
#1548

### CODE REVIEW

**Comment by azuredream** [comment]
Hi @romange , I've added two use cases for STORE and STOREDIST. They store the query result(with hash or dist) into a key(zset).
Similarly, GEOSEARCHSTORE, GEORADIUS also support this.

**Comment by romange** [comment]
@azuredream sure, I will take a look. Meanwhile please see https://redis.io/commands/geosearch/ examples.
they do not work because distance units parsing is case sensitive. Would you like to fix it?
And, if you do - please see if `CmdArgParser` class can simplify the parsing code (I forgot it was introduced lately).
See https://github.com/dragonflydb/dragonfly/pull/2148#discussion_r1387223367 for example on how it can help.

**Comment by azuredream** [comment]
Thanks. I'll fix it.

**Comment by romange** [comment]
@azuredream  I think I fixed the transactional code to support GEORADIUSBYMEMBER.
The command code must be changed though. It should become a two-hop operation similarly to ZInterStore for example

**Comment by romange** [comment]
of course you need two hops only if the STORE option exist, otherwise you proceed like today.

**Comment by azuredream** [comment]
Thanks, I'll update my code accordingly. 
Please note that in GEOSEARCHSTORE, the destination is not the last key.
_GEOSEARCHSTORE destination source <FROMMEMBER member |
  FROMLONLAT longitude latitude> <BYRADIUS radius <M | KM | FT | MI>
  | BYBOX width height <M | KM | FT | MI>> [ASC | DESC] [COUNT count
  [ANY]] [STOREDIST]_

**Comment by azuredream** [comment]
Hi Romange,
PR updated. 
I encountered a wired issue. This command works in CLI:
127.0.0.1:6379> GEORADIUSBYMEMBER Europe Madrid 700 KM STORE test1
(integer) 2
(15.54s)
127.0.0.1:6379> zrange test1 0 -1
1) "Madrid"
2) "Lisbon"

The first unit test case worked as well.
`GEORADIUSBYMEMBER Europe Madrid 700 KM WITHCOORD WITHDIST`

However, **the second test case failed. Please note that this command worked in CLI.**
`GEORADIUSBYMEMBER Europe Madrid 700 KM STORE store_key`
[ RUN      ] ZSetFamilyTest.GeoRadiusByMember
get resp: ERR Member not found
F20231114 21:37:55.006270 2607605 test_utils.cc:466] Check failed: RespExpr::STRING == int(resp.type) (0 vs. 6) [GEORADIUSBYMEMBER, Europe, Madrid, 700, KM, STORE, store_key]

When I used GDB to run the test case line by line, it worked again.

I suppose it's something to do with the schedule-execute model.
When I use `STORE` option, there will be 3 transactions while 2 without STORE.
It's confusing to me that the test case failed at the first transaction (get key from db), not the last one.
I'd appreciate it if you could share your thought on this. Thanks!

**Comment by romange** [comment]
Hello @azuredream , thank you for continuing working on this. Can you please try rebasing the branch and fixing the conflicts?

**Comment by azuredream** [comment]
I'll reopen a new PR based on the latest main.

**Pull request closed without merging**
