### PR TITLE
fix(server): client pause work while blocking commands run

### LINKED ISSUE #2576: support client pause with blocking command
Today when blocking command is running we are getting timeout on pausing clients

### LINKED ISSUE #2661: Bug: do not squash blocking commands in Service::DispatchManyCommands
Today we squash  blocking commands in Service::DispatchManyCommands and return error on the squeshed command as blocking commands can not run as part of multi transaction

### PR DESCRIPTION
**Pull request by adiholden**
fix #2576 
fix #2661

### CODE REVIEW

**Review by dranikpg — APPROVED** [review]
I see, we can ignore them because no updates are possible, they can't be unlocked.

The only issue I see:
- While we wait with the dispatch tracker, some command unblocks a blocking one
- The blocking one starts doing stuff, but we didn't track it, so we don't wait for it

**Review by BorysTheDev — DISMISSED** [review]

**Comment by adiholden** [comment]
@dranikpg you are right. Have a suggestion how we can fix this?

**Comment by dranikpg** [comment]
@adiholden My only idea would be to call it again, maybe we can do it only if we have blocking commands.

1. Run dispatch tracker
2. Wait for non-blocking to finish
3. All blocked commands should be running within some suspension points, milliseconds (?) 🤷🏻‍♂️ Maybe we can track them somehow, like with blockingcontroller->awakened
4. Run dispatch tracker again to catch all non blocking ones

so maybe
```
Dispatch {  
  tracker.Track()
}
tracker.Wait()

while Dispatch { blocking_controller -> queue_map > 0 }
  sleep x ms

Dispatch {  tracker.Track() } // wait for two-hop commands like brpoplpush to finish
tracker.Wait()
```

**Comment by dranikpg** [comment]
We also have one more problem, namely BLPOP on it's started phase is not counted as blocking, it has two hops:

1. Find key
-- we use Tracker.Track() here, it doesn't recognize it as blocked, but it _will_ block  --
2. WaitOnWatch

Will report on this as well 🤔🤔🤔🤔

**Comment by adiholden** [comment]
> We also have one more problem, namely BLPOP on it's started phase is not counted as blocking, it has two hops:
> 
> 1. Find key
>    -- we use Tracker.Track() here, it doesn't recognize it as blocked, but it _will_ block  --
> 2. WaitOnWatch
> 
> Will report on this as well 🤔🤔🤔🤔

So actually having 2 hops in blpop also makes CancelBlocking funciton bugy

**Comment by dranikpg** [comment]
This is so clumsy 😭 

```c++
// First, tell everything in the future to pause
Dispatch ( ) { paused = true; }

// Now wait for all blocking setup do dissolve and only then track regular commands
do { 
  ok = Dispatch({
    if (any_blocking_setup)
     return false;
    tracker.TrackOnThread();
    return true;
  })
} while (!ok)
tracker.Wait()

// The regular commands might have triggered a wave of unblocks, wait for all of them to finish and track again (is it needed? 🤔 )
do { 
  ok = Dispatch({
    if (blocking_controller->awakened > 0)
     return false;
    tracker.TrackOnThread();
    return true;
  })
} while (!ok)
tracker.Wait()
```

Here we only need to set `any_blocking_setup` that is incremented when a coordinator is initialized as blocking and decremented when it concludes or suspends

**Comment by dranikpg** [comment]
Maybe it's simpler just to do busy looping

```c++
Dispatch { paused = true }
do {
  ok Dispatch {
    if (num_dispatch - num_blocking > 0) return false
    if (blocking_controller -> awakened > 0) return false
    return true;
  }
  if (!ok) sleep(1ms)
} while (!ok)
```

**Comment by adiholden** [comment]
@dranikpg I pushed a fix which will solve both of the seraios you mentioned above:
1. if a blocking transaction becomes unblocked is solved by running AwaitPauseState inside Transaction::WaitOnWatch after we are waking up from blocking
2. the 2 hops problem with the blpop is fixed by running the tracker twice if we reached the timeout, as at the first time we run the TrackAll the transaction is blocking and we will not send a checkpoint

**Comment by dranikpg** [comment]
will review in 30 mins

**Review by dranikpg — DISMISSED** [review]
I suggest to merge it. With a very low probably we can time out spuriously or wait one second... But most importantly it looks correct

**Comment by dranikpg** [comment]
But please add a comment above pause why it works with blocking, even though it ignores them 😅

**Review by dranikpg — APPROVED** [review]

**Pull request merged**
