### PR TITLE
fix(json_family): Add test case when jsonpathv2 is false to the json family tests

### PR DESCRIPTION
**Pull request by BagritsevichStepan**
relates to the #3285

### CODE REVIEW

**Comment by romange** [comment]
Dude, it's much simpler to add to ci.yaml this specific unit test  with the flag. We already do it from time to time.
see for example,
```
./multi_test --multi_exec_mode=1
./multi_test --multi_exec_mode=3
```

**Review by kostasrim — APPROVED** [review]
nice, just merge #3285 first :)

**Comment by kostasrim** [comment]
didn't see @romange comment, plz move on with that :)

**Comment by kostasrim** [comment]
> Dude, it's much simpler to add to ci.yaml this specific unit test with the flag. We already do it from time to time. see for example,
> 
> ```
> ./multi_test --multi_exec_mode=1
> ./multi_test --multi_exec_mode=3
> ```

the only downside is that it doesn't run locally though with `ctest`

**Pull request closed without merging**
