### PR TITLE
feat(config): support setting multiple parameters

### PR DESCRIPTION
**Pull request by andydunstall**
As part of https://github.com/dragonflydb/dragonfly/issues/2038, looking at how to apply multiple config values at once, such as `CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem` (currently only the first config-value pair is updated)

Simply iterating over `config_registry.Set` won't work as it will update the first flag, run the first callback, update the second flag, run the second callback... Therefore the first callback will still have the old value for the other updated flags, which doesn't work when you need to set multiple flags at once for the config to be valid (eg in the TLS case).

So instead looking at updating the flags first, then running the callbacks. So in the TLS case it would set all configured TLS flags, then run the callbacks to reconfigure the SSL context.

Also looking at Redis `CONFIG SET`, they roll back the updated config if it is invalid rather than doing a partial update. (Roll backs aren't as useful now, but will be useful if we add TLS, say the key is valid but certificate is invalid, you'd want to revert both...)

This doesn't work great in Dragonfly since other code could directly query a flag mid update given flags don't seem to be locked (maybe this is why we currently only support setting one parameter? though if all flags registered with config registry are only updated via registered callback it should be ok?)... Since the config registry also only locks each `Set`, parallel `CONFIG SET`s could cause issues, though assuming locking the config registry for the whole command isn't great either...

So maybe this isn't worth doing and we just accept TLS config must be updated one parameter at a time in a way that's valid... But was playing about with so figured worth adding a draft PR anyway to get your thoughts (or see if there's a better approach here?)... cc @romange

### CODE REVIEW

**Comment by dranikpg** [comment]
I like the idea

> Since the config registry also only locks each Set, parallel CONFIG SETs could cause issues, though assuming locking the config registry for the whole command isn't great either...

Why isn't it great? You want to execute all config changes "at once", so there is really no other option

And this is why I would move all of the implementation to the config registry and even internalize this transaction behaviour, so

Registry Set becomes

```python
def registry_set(self, new_configs: list) -> StatusCode:
  lock(self)
  cbs = []
  backup = []

  for name, value in new_configs: 
    cb, flag = get_for_name(name)
    backup.push(flag.old())
    if flag.parse(value) != Ok: 
      return err
    cbs.push(cb)

  -- here you updated all the values but didn't apply any --

  for ((_, value), cb) in zip(new_configs, cbs)
    if cb.apply() != Ok:
      rollback()
      return err
```

and CONFIG SET would in fact just remain the same 😎 

```python
new_config = [(parser.Next(), parser.Next()) for args.subspan(3?)]
code = registry.apply(new_config)
reply(code)
```

which at the end does the job with minimal changes and complexity

**Comment by andydunstall** [comment]
Ok great thanks - I'll give that a go

**Comment by romange** [comment]
Do I recall correctly that a certificate is used to create the private key? I.e if the certificate is created, the key must be replaced as well but the same certificate can be used for multiple keys?

**Comment by kostasrim** [comment]
> Also looking at Redis CONFIG SET, they roll back the updated config if it is invalid rather than doing a partial update. (Roll backs aren't as useful now, but will be useful if we add TLS, say the key is valid but certificate is invalid, you'd want to revert both...) 

You don't need to revert anything. I think there is a cleaner solution with rollback's being done implicitly.

What we want is basically to update the config flag values if and only if, `CreateSslServerCntx` succeeds and not the other way around (that is, first update the config, if `CreateSslServerCntx` fails then rollback, if not then keep the update). The later chore requires a rollback, whereas the first one doesn't (it's implicit, we never update the flags and therefore if we fail to set them, it's like the OP never happened -- the rollback part). So what I propose is:

1. Overload `ConfigRegistry::Set` to update all the configs in one go. Acquire a lock, and update all of the flags in one go.
2. `ServerFamily::Config` Add a special handler here, to call the overload of `Set` when the flag is `tls` related
3. Before you call the overload (set) above, first try to update the `SSL configuration`. If it fails, do not call the overloaded `Set` and return an error (the rollback part). If it succeeds, update the flags in one go via the overloaded set.
4. step (3) is racy, because there can be multiple `config sets` concurrently. Even though the chances of this happening is zero, you can use the `WithLock` pattern (see how it's done in ACL), that basically allows to Lock the registry while you are updating the SSL config. 

This is a far simpler solution since it doesn't require explicit rollbacks on failures.

@dranikpg @andydunstall what do you say?

> Do I recall correctly that a certificate is used to create the private key? I.e if the certificate is created, the key must be replaced as well but the same certificate can be used for multiple keys?

and:

> So yeah I guess you can update the cert without the key

The `certificate` is the `public key`. To generate the public key, you need the private key, because otherwise how would the private key know how to decrypt it ? (it would be useless otherwise). So the answer should be, you can't just update the public key without the private key. You can keep the private key the same but not vice versa (check how to generate keys with openssl)

**Comment by dranikpg** [comment]
How it is simpler if it turns it into a corner case (which I'd always prefer to avoid) 🤯 Rolling back is essentially just calling Set again with the old value pairs and asserting it succeeds, that's it

**Comment by andydunstall** [comment]
> The only concern I have about rollback is the following: what if the original tls files were removed after start? Is that possible? Then a rollback would fail as well

Yeah makes sense - or if the certificate is updated at the same path

Could keep generic and only roll back the completed callbacks rather than all callbacks - then the TLS callback just doesn't update the SSL context if the new key/cert is invalid?

**Comment by kostasrim** [comment]
> How it is simpler if it turns it into a corner case (which I'd always prefer to avoid) 🤯 Rolling back is essentially just calling Set again with the old value pairs and asserting it succeeds, that's it

Because rollbacks is a generic mechanism that we don't need for the config registry. There is no other flag in DF that needs rollbacks atm and introducing a generic solution for a corner case is overengineering and unnecessary complicated. With rollbacks, each time I have to read the registry code, I know also need to understand how rollbacks are being done just to handle a corner case -- IMO a cognitive overhead that is no worth paying for just a corner case.

> How it is simpler if it turns it into a corner case (which I'd always prefer to avoid)

There is an inherent cost when introducing generic solutions for corner cases. A corner case is a corner case and I think it's better if it's handled explicitly than implicitly (by a generic mechanism that serves to *only* be used for the corner case).

p.s. I am not against rollbacks, I would like them if they were used frequently in this context. But they don't, and having a generic mechanism handling only a single corner case is not simpler in my eyes.

p.s.2 I understand this is also a preference so I am not strongly advocating this -- just thinking out loud!

**Comment by dranikpg** [comment]
> Could keep generic and only roll back the completed callbacks rather than all callbacks

That sound like a working solution, right 👍🏻 

> Because rollbacks is a generic mechanism that we don't need for the config registry.

Because we just don't support most flags within it 😛 The next moment we decide to add support for any fallible parameter, the corner case will be duplicated

Anyways, lets let Roman and Andy decide with this 🙂

**Comment by kostasrim** [comment]
@dranikpg We can avoid the rollbacks altogether, see my edit :)

**Comment by andydunstall** [comment]
> lets let Roman and Andy decide with this

Given I've already started on rollbacks may as well keep going

I don't think rollbacks are really that complex? If the config is invalid the update won't be applied so it doesn't matter if we're calling multiple times (which is what Redis is doing)

It also seems nice to avoid partial config updates?

Say you want to includes max memory and set a password at the same time, you may be supprised to find the command failed but max memory was still increased? (Maybe a trivial example but could see it being an issue at some point?)

**Comment by romange** [comment]
Why do we need to update at once though? We always have a single agent configuring the process, no? So we should not expect any artefacts related to lack of atomicity

**Comment by romange** [comment]
how "CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem" and "CONFIG SET tls-cert-file cert.pem tls-key-file key.pem" will behave when the initial state for `tls` is false. Does former apply the changes and the latter does not apply? What happens if then "config set tls true" is applied and it fails? we do not expect rollbacks to config set values for "tls-cert-file", "tls-key-file", right ?
what i am saying is that implicitly applying config values for a feature that requires multiple flags is gonna be ambiguous anyway.

**Comment by andydunstall** [comment]
> Why do we need to update at once though? We always have a single agent configuring the process, no? So we should not expect any artefacts related to lack of atomicity

I'm not sure I follow

> how "CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem" and "CONFIG SET tls-cert-file cert.pem tls-key-file key.pem" will behave when the initial state for tls is false

`CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem` will create the SSL context with the given cert and key then enable TLS

`CONFIG SET tls-cert-file cert.pem tls-key-file key.pem` won't do anything if TLS isn't enabled, or if it is enabled it will update the cert and key. If TLSs wasn't enabled, the flags will still be updated, but when you eventually enable TLS it will create the SSL context (then if the cert/key is invalid enabling TLS will be rolled back)

> What happens if then "config set tls true" is applied and it fails?

If the cert/key is invalid, TLS won't be enabled (the SSL context won't be set)

> what i am saying is that implicitly applying config values for a feature that requires multiple flags is gonna be ambiguous anyway

I'm not really sure I follow where the issue is?

Yeah we could end up with flags pointing to invalid cert/key when TLS isn't enabled, but then you won't be able to update TLS so I don't see the issue?

Are you against `CONFIG SET` supporting multiple conf-value pairs or the implementation approach?

**Comment by kostasrim** [comment]
@andydunstall I also have a couple of more questions -- I think we have a broader set of issues:

1. `SSL_CTX` is set in `dragonfly_listener.cc` and also each new connection gets a copy of the context `return new Connection{protocol_, http_base_.get(), ctx_, service_};` My number one concern here, is that if you update the `ctx` what happens to the already existing connections that use the old `ctx_`, do they dangle and DF crashes? Do we evict them? 

2. What stops the `listeners` create new connections while a flag is being set `CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem` concurrently? Does that mean we need to lock the `listener` ? 

3. If (2) is true, `CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem` is problematic because the `cb` will lock the listeners in two steps (races).

4. For cases like `CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem`, I imagine that both the callbacks will call `CreateSslServerCntx` to create a new cntx. But here, there is a problem as well. That if both call this function, it means that we call it twice. One to set the `cert file` and one to set the `key` file. This could crash (I think openssl verifies the relationship between them but I could be wrong), because `DFLY_SSL_CHECK(1 == SSL_CTX_use_certificate_chain_file(ctx, tls_cert_file.c_str()));` would use the `old` value while the `DFLY_SSL_CHECK(1 == SSL_CTX_use_PrivateKey_file(ctx, tls_key_file.c_str(), SSL_FILETYPE_PEM));` would use the new one and vice versa. Isn't this a problem?


5. Does redis support setting the `SSL` context at runtime via `CONFIG SET`? 

cc: @romange @dranikpg

**Comment by andydunstall** [comment]
> SSL_CTX is set in dragonfly_listener.cc and also each new connection gets a copy of the context return new Connection{protocol_, http_base_.get(), ctx_, service_}; My number one concern here, is that if you update the ctx what happens to the already existing connections that use the old ctx_, do they dangle and DF crashes? Do we evict them?

The new SSL context only applies to new connections, we don't change existing connections TLS (which matches how Redis works) (see old WIP branch: https://github.com/andydunstall/dragonfly/pull/2/files)

> What stops the listeners create new connections while a flag is being set CONFIG SET tls true tls-cert-file cert.pem tls-key-file key.pem concurrently? Does that mean we need to lock the listener ?

The only change here is the listeners SSL context - other config updates like max clients seem to update the context without locking

> Does redis support setting the SSL context at runtime via CONFIG SET?

Yes via a similar approach - update the listeners SSL context and swap

(still working on other questions...)

**Comment by andydunstall** [comment]
> That's a data race between ReconfigureTls and NewConnection because nobody stops the concurrent read/write to ctx_.

Ok so we need to use a mutex here then? I'm still not sure why setting max connections doesn't need a mutex...

> Also you free the ctx_, dangling all the open connections.

Hmm I think `SSL_CTX_free` just decrements a reference count - though thinking about it again not sure if thats thread safe...? (I added that draft branch then figured it was worth looking at `CONFIG SET first so haven't spend too long on the TLS config - though seems like TLS is more complex than I expected...)

> Sorry for bombarding with too many question, it's a feature that can cause a lot of trouble so I am doing my best for us to no miss anything

No this is really useful - thanks for looking into it!

**Comment by kostasrim** [comment]
> Ok so we need to use a mutex here then? I'm still not sure why setting max connections doesn't need a mutex...

That's a data race over there as well:

```

Proactor 0 : RunAcceptLoop()                         Proactor 1: `CONFIG SET maxlients 44`

if (prev_connections >= max_clients_)           sets max_clients_ here
```

According to the C++ standard that's a data race over there :) 

> Ok so we need to use a mutex here then

Probably yes, but I am not happy with this and I don't know how this will affect the hot path. I am bringing this up so I can have input from the rest of the team as well :) 

> Hmm I think SSL_CTX_free just decrements a reference count -

I am not sure either we need to check :man_shrugging: 

>  TLS config - though seems like TLS is more complex than I expected

It's a pain, for me it was dreaded to work with it. Cryptography people are REALLY smart and awesome, but openssl API and Docs is terrible :stuck_out_tongue: 

> though I guess your point is if we can't get TLS working then theres no point adding this config change?

I am not sure, I just want us to have answers before we proceed. I don't want you to do circles back and forth just because we missed something. Again, take my words with a grain of salt, but I want for us to be sure since this to me looks a little bit more complicated that originally thought it would be

> This is really useful - thanks for looking into it!

Thank you for baring with me, as I said I don't want you to end up going back and forth because we missed something :pray:

**Comment by andydunstall** [comment]
> According to the C++ standard that's a data race over there :)

Ah ok :(

> I don't know how this will affect the hot path

Does accepting connections count as the hot path? Do we expect a high connection rate? (I'm not disagreeing just curious :slightly_smiling_face:)

Sounds like the biggest issue is that the server SSL context is being accessed by multiple threads to create `tls::TlsSocket` in `Connection::HandleRequests`? Though could we just move that into the listener proactor, so the connection procactor only accesses its own created connection context, not the server context? eg add a `TlsConnection` that overrides `SetSocket`?

**Comment by romange** [comment]
Lets make an order here. 

1. There is a data race bug with SetMaxClients which potentionally can lead to UB.  It's not very severe and easy to fix by documenting that SetMaxClients/GetMaxClients must run within a proactor thread that handles the accept `socket()` of `ListenerInterface`. It's also easy to fix by adapting `SetMaxClients` inside server_family.cc accordingly.
2. I agree that we should create `SSL_CTX` object aside, check if it's valid and only then to switch. I also concur that dragonfly code needs to add refcount semantics with its SSL_CTX object.
3. Regarding rollbacks and config set, I have a suggestion to avoid creating SSL_CTX object upon updating key/cert flags and only creare the new object when tls=true is set. This way we can separate the config update and the SSL_CTX reload and we won't need to support multiple arguments, we won't need to rollback etc. The main motivation for this suggestion is relative simplicity. By convention we will agree `CONFIG SET tls true` will always try to reload CTX and to return an error if it did not succeed. 

wdyt?

**Comment by andydunstall** [comment]
Ok sure 1 and 2 sound good to me

I'm not sure I understand why we don't want to add support for `CONFIG SET` to support multiple parameters - if we don't we should explicitly reject config attempts with multiple parameters and [update the docs](https://www.dragonflydb.io/docs/command-reference/server-management/config-set). I agree it adds some complexity, though its just doing the same thing as Redis and seems like a useful feature?

Happy to leave it and just implement '3' though I don't really understand the issue

So updating tls-cert-file and tls-cert-path will update the flags but not reload the context - then we wait for 'tls true' to reload?

**Comment by kostasrim** [comment]
@andydunstall 

1. You don't have to worry about the data race -- I will take care of it.
2. > I agree it adds some complexity, though its just doing the same thing as Redis and seems like a useful feature? 

So far nobody has asked for it :shrug: I would defer these kind of improvements until somebody in the community needs it. There are benefits to that approach

3. Or we add the naive implementation of iterating over each pair and doing registry.Set 
Not really happy about this since this would imply we could use it for other configs as well. 

Just to be clear I am not against support for multiple arguments in config set but I do think that a) it's beyond the scope of what we need b) it's better to leave these kind of improvements for when the community requests them

4. I like Roman's approach on (3). Recently I suggested the thing with `CONFIG SET aclfile`. I didn't suggest it here because for some reason I considered it a defacto that we need multiple arguments for `config set` but now that things are clearer, it's not really required.

**Comment by andydunstall** [comment]
Will close this as agreed not needed

(Sorry i probably made this more effort than it needed to be... :sweat_smile:)

**Comment by romange** [comment]
Thanks Andy!
No need to be sorry - you discovered several issues that need to be addressed and I think it was a good discussion.

**Comment by kostasrim** [comment]
> (Sorry i probably made this more effort than it needed to be... 😅)

No dude you really did well, I said this internally as well, these kind of discussions are really fruitful for everybody. We make assumptions, bring ideas, we communicate and reiterate and that's how we all grow. Plus, we found a bug as well ;) 

Good work buddy :rocket:

**Pull request closed without merging**
