### PR TITLE
feat(docker): try increasing a memlock limit in the container

### LINKED ISSUE #57: Helm-Chart
Hey Folks,

I just stumbled across this insane project - great work so far! 🚀  

I was wondering if you guys are already working on a `helm`-Chart in order to deploy `dragonfly` to Kubernetes?
It would be a lot easier for us to test `dragonfly` in our environment then.

Best regards!

### PR DESCRIPTION
**Pull request by romange**
This should solve the awkward command overrides in K8S scripts.
Fixes #57.

### CODE REVIEW

**Review by TamCore — APPROVED** [review]
LGTM

But the placement doesn't really matter. Appending a `|| true`would make it work with every placement :)

**Comment by romange** [comment]
that's true :) did not want to spend time on figuring how to mix `||` and redirects together :)

**Comment by ryanrussell** [comment]
Just a note on `ulimit` -- You may need to set this at the hypervisor level also.

> "If you do net set the value when running the container, the ulimit value displayed within the container comes from the host OS. The question is then why are you seeing a different value when running the same command from the host?

> This is because when running the command in the host, it is showing its soft limit. On the other hand, the value that the container is showing is the hard limit of the host OS.If you do net set the value when running the container, the ulimit value displayed within the container comes from the host OS. The question is then why are you seeing a different value when running the same command from the host?

> This is because when running the command in the host, it is showing its soft limit. On the other hand, the value that the container is showing is the hard limit of the host OS."

See https://stackoverflow.com/questions/46211558/ulimits-in-docker-host-vs-container

Some good things to check if you're running `docker-compose`, `swarm mode` or `k8s`:

1) Hypervisor ulimit
ulimit -Hn

2) Docker daemon ulimit(/etc/docker/daemon.json)
```bash
systemctl show docker | grep NOFILE
LimitNOFILE=infinity
LimitNOFILESoft=infinity
```
See: https://stackoverflow.com/questions/71952645/docker-default-ulimit-nofile-setting

3) Set at YAML/Dockerfile level
As implemented in Dockerfile `entrypoint.sh` in #114 

@romange It would be a nice-to-have to make a specific FAQ around `ulimit` and cover bare metal, docker-compose and k8s examples. Fully expect this issue will re-surface many times in various flavors.

**Comment by romange** [comment]
@ryanrussell  I just want to avoid overrides like the one below. And it works with the overrides, it means it will work with this fix.
but you are right that in the worst case one needs to fix the host as well.

```yaml
spec:
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          command: ["/bin/sh"]
          args: ["-c", "ulimit -l unlimited && dragonfly --logtostderr"]
```

**Pull request merged**
