### PR TITLE
refactor(workflow): changes default permissions to read for few workflows increasing security

### PR DESCRIPTION
**Pull request by BLANKatGITHUB**
well sorry for trouble, I just add all the changes related to workflows in this one pr, I will make separate pr to add new workflows.
I accidentally deleted my main branch closing previous pr , I hope you can over look it this time I am kinda new , It wont happen again.

### CODE REVIEW

**Comment by BLANKatGITHUB** [comment]
@romange  I cant run workflows if this repo has restriction for new contributors to run workflow on their public repo can you please allow me to do that.

**Comment by romange** [comment]
@BLANKatGITHUB  hello. are you planning to work on this PR?

**Comment by BLANKatGITHUB** [comment]
umm sure
but for some reason I can't run and test  workflows in my branch for reason , but you can commit these changes which does not affect the workflows directly , I will add the other workflows later when I get permission to run workflow in my branch.

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
Thanks!

**Pull request merged**
