### PR TITLE
<bug>(cmake): Support FreeBSD sed

### PR DESCRIPTION
**Pull request by yonas**

### CODE REVIEW

**Review by romange — DISMISSED** [review]

**Comment by romange** [comment]
Thanks!

**Comment by romange** [comment]
Did not work 🤷🏼

**Comment by yonas** [comment]
The debug info is in `/__w/dragonfly/dragonfly/build/third_party/src/dconv_project-stamp/dconv_project-patch-*.log`. Is there any way you can copy/paste that here?

**Comment by romange** [comment]
yeah, i checked it locally on my linux machine. for some reason it takes the `if (UNIX AND NOT LINUX)` branch.

**Pull request closed without merging**
