### PR TITLE
fix(transaction): Reset reverse index in multi-tx

### LINKED ISSUE #2083: test_parser_while_script_running fails in debug build
**Describe the bug**
Assertion fails in: 
```
transaction.cc:297] Check failed: args_[i] == ArgS(args, reverse_index_[i]) (m5 vs. m6)
```

**Reproducible Code Snippet**

Just run locally on debug build: `python3 -m pytest dragonfly/connection_test.py -k "test_parser_while_script_running"`

```
41497➜ Check failure stack trace: ***
41497➜    @     0x56000d164115  google::LogMessage::Fail()
41497➜    @     0x56000d16405b  google::LogMessage::SendToLog()
41497➜    @     0x56000d163830  google::LogMessage::Flush()
41497➜    @     0x56000d1676a8  google::LogMessageFatal::~LogMessageFatal()
41497➜    @     0x56000c665793  dfly::Transaction::InitByKeys()
41497➜    @     0x56000c6668c8  dfly::Transaction::InitByArgs()
41497➜    @     0x56000bfefa60  dfly::MultiCommandSquasher::ExecuteStandalone()
41497➜    @     0x56000bff353b  dfly::MultiCommandSquasher::Run()
41497➜    @     0x56000ba8176c  dfly::MultiCommandSquasher::Execute()
41497➜    @     0x56000ba0b634  _ZZN4dfly7Service20DispatchManyCommandsEN4absl12lts_202308024SpanINS3_INS3_IcEEEEEEPN6facade17ConnectionContextEENKUlvE_clEv
41497➜    @     0x56000ba0c0fd  dfly::Service::DispatchManyCommands()
41497➜    @     0x56000ca06228  facade::Connection::DispatchFiber()
41497➜    @     0x56000ca0a0e9  _ZZN6facade10Connection27LaunchDispatchFiberIfNeededEvENKUlvE_clEv
41497➜    @     0x56000ca11c22  _ZSt13__invoke_implIvZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
41497➜    @     0x56000ca1192a  _ZSt8__invokeIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS4_DpOS5_
41497➜    @     0x56000ca10e35  _ZSt12__apply_implIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE
41497➜    @     0x56000ca10eb2  _ZSt5applyIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_St5tupleIJEEEDcOT_OT0_
41497➜    @     0x56000ca110c2  _ZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEE4run_EON5boost7context5fiberE
41497➜    @     0x56000ca10087  _ZZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEEC4IN5boost7context21basic_fixedsize_stackINS9_12stack_traitsEEEEESt17basic_string_viewIcSt11char_traitsIcEERKNS9_12preallocatedEOT_OS5_ENKUlONS9_5fiberEE_clESO_
41497➜    @     0x56000ca12791  _ZSt13__invoke_implIN5boost7context5fiberERZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEEC4INS1_21basic_fixedsize_stackINS1_12stack_traitsEEEEESt17basic_string_viewIcSt11char_traitsIcEERKNS1_12preallocatedEOT_OS9_EUlOS2_E_JS2_EESM_St14__invoke_otherOT0_DpOT1_
41497➜    @     0x56000ca12523  _ZSt8__invokeIRZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEEC4IN5boost7context21basic_fixedsize_stackINSA_12stack_traitsEEEEESt17basic_string_viewIcSt11char_traitsIcEERKNSA_12preallocatedEOT_OS6_EUlONSA_5fiberEE_JSO_EENSt15__invoke_resultISL_JDpT0_EE4typeESM_DpOST_
41497➜    @     0x56000ca123df  _ZSt6invokeIRZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEEC4IN5boost7context21basic_fixedsize_stackINSA_12stack_traitsEEEEESt17basic_string_viewIcSt11char_traitsIcEERKNSA_12preallocatedEOT_OS6_EUlONSA_5fiberEE_JSO_EENSt13invoke_resultISL_JDpT0_EE4typeESM_DpOST_
41497➜    @     0x56000ca121fd  _ZN5boost7context6detail12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEEC4IS6_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSD_EUlOS3_E_E3runEPv
41497➜    @     0x56000ca11f3b  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN6facade10Connection27LaunchDispatchFiberIfNeededEvEUlvE_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSE_EUlOS4_E_EEEEvNS1_10transfer_tE
41497➜    @     0x7f6eff36524f  make_fcontext
41497➜ SIGABRT received at time=1698403447 on cpu 0 ***
41497➜ @     0x7f6efde969fc  (unknown)  pthread_kill
41497➜    @     0x56000d1e9273         64  absl::lts_20230802::WriteFailureInfo()
41497➜    @     0x56000d1e94cd         96  absl::lts_20230802::AbslFailureSignalHandler()
41497➜    @     0x7f6efde42520  (unknown)  (unknown)

```

### PR DESCRIPTION
**Pull request by dranikpg**
Fixes #2083

### CODE REVIEW

**Comment by dranikpg** [comment]
Btw, how come this test didn't fail (run) on CI? 🤔

**Comment by romange** [comment]
@dranikpg if you already are asking the question, can you please add a test :)

**Comment by kostasrim** [comment]
@dranikpg the script runs normally on the CI and it passes so my two cents would be that something is wrong with pipelining/squashing (beyond clearing the index) and probably it has to do with timing. It's worth checking this out. Did it also fail for you locally?

**Comment by dranikpg** [comment]
Yes, it must have been because of timings, it seems like the CI client was to slow to accumulate a pile of commands, added some tests

**Review by adiholden — APPROVED** [review]

**Review by kostasrim — APPROVED** [review]

**Pull request merged**
