### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by worldsoup**
Signed-off-by: Nick Gottlieb <ngottlieb1@gmail.com>

### CODE REVIEW

**Comment by worldsoup** [comment]
@odedponcz @romange I made some updates to the readme...could one of you please review?

**Comment by romange** [comment]
@worldsoup your presubmit check are failing. Probably due to trailing whitespace.

**Comment by worldsoup** [comment]
@romange ok I've fixed the white space

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
Thanks Nick!

**Pull request merged**
