### PR TITLE
fix(zset): Better memory consumption calculation

### LINKED ISSUE #2808: memory usage ~wrong memory usage reporting
**Describe the bug**
Adding 100k sorted set members with simple increasing counter eats 25MB vs 8.5MB at redis
( zero score for all elements give also x3 mem )
**To Reproduce**
1. Insert 100k records using ZADD TEST SCORE MEMBER with for loop
2. Query records MEMORY USAGE TEST

**Expected behavior**
Expected to consume memory as redis or less

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Kernel: Linux work1 5.10.16.3-microsoft-standard-WSL2
 - Containerized: WSL2
 - Dragonfly Version: v1.14.3-ea6b0ca6772e05c251546ec873bf46ef97d5c588

**Reproducible Code Snippet**
```
  //Javascript node redis 
  client = await createClient({ url: "redis://localhost" })
    .on('error', err => console.log('Redis Client Error', err))
    .connect();

  for (var i = 0; i < 100_000; i++)
      await client.zAdd( "TEST2", {score : i, value:i.toString()} );
      //or comment upper line and uncomment below line for adding with zero score
      //await client.zAdd( "TEST", {score : 0, value:i.toString()} );
```

### PR DESCRIPTION
**Pull request by chakaz**
Fixes #2808

### CODE REVIEW

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
What was the bug?

**Comment by chakaz** [comment]
> What was the bug?

To quote from `NodeCount()`:

```cpp
  size_t NodeCount() const {
    // number of nodes in the tree (usually, order of magnitude smaller than Size()).
    return num_nodes_;
  }
```

So we were wrong by "an order of magnitude". Unless I got the implementation wrong, but I think I got it right (we allocate per node, not per item)

**Comment by chakaz** [comment]
@romange ok to merge?

**Comment by romange** [comment]
Yes!

**Pull request merged**
