### PR TITLE
chore: set serialization_max_chunk_size to 1 byte

### PR DESCRIPTION
**Pull request by kostasrim**
Update the flag for extreme testing. We should remove this before the release.

* set serialization_max_chunk_size to 1 byte

### CODE REVIEW

**Comment by dranikpg** [comment]
CI failures go brrrr 🏗️ 😆

**Comment by kostasrim** [comment]
> CI failures go brrrr 🏗️ 😆

That's what I said.... let's see

**Comment by dranikpg** [comment]
It fails in quite a few interesting places 😱

**Comment by kostasrim** [comment]
> It fails in quite a few interesting places 😱

Half of them are fixed half of them will be fixed soon in another PR. 

IMO not that interesting, just forgot to make the necessary changes in some places.

IMO2 I was expecting timeouts but at least we got so nice corner cases caught :)

**Review by BorysTheDev — APPROVED** [review]

**Pull request merged**
