### PR TITLE
fix: Do not attempt to defrag `StringSet` as a `StringMap`

### LINKED ISSUE #4167: crash in dense set defragmentation
See below:

```
#3  0x00007ffff7c4526e in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
#4  0x00005555561da46e in absl::lts_20240116::AbslFailureSignalHandler(int, siginfo_t*, void*) ()
#5  <signal handler called>
#6  0x0000555555b362c3 in mi_slice_first (slice=0x65e19793ae006108) at /__w/dragonfly/dragonfly/build-release/third_party/mimalloc/include/mimalloc/internal.h:471
#7  _mi_segment_page_of (p=0x65e19793af000000, segment=<optimized out>) at /__w/dragonfly/dragonfly/build-release/third_party/mimalloc/include/mimalloc/internal.h:486
#8  _mi_ptr_page (p=0x65e19793af000000) at /__w/dragonfly/dragonfly/build-release/third_party/mimalloc/include/mimalloc/internal.h:502
#9  mi_heap_page_is_underutilized (heap=0x339c2110800, p=p@entry=0x65e19793af000000, ratio=0, ratio@entry=0.800000012) at /__w/dragonfly/dragonfly/build-release/third_party/mimalloc/src/alloc.c:581
#10 0x0000555555b33906 in zmalloc_page_is_underutilized (ptr=ptr@entry=0x65e19793af000000, ratio=ratio@entry=0.800000012) at ../src/redis/zmalloc_mi.c:179
#11 0x0000555555a6192a in dfly::StringMap::ReallocIfNeeded (this=<optimized out>, obj=0x339c27d1a03, ratio=0.800000012) at ../src/core/string_map.cc:198
#12 0x0000555555a61b02 in <lambda(auto:25*)>::operator()<dfly::DenseSet::DensePtr> (ptr=0x339c2188640, __closure=0x339f234d7c0) at ../src/core/string_map.cc:304
#13 std::_Function_handler<void(dfly::DenseSet::DensePtr*), dfly::StringMap::iterator::ReallocIfNeeded(float)::<lambda(auto:25*)> >::_M_invoke(const std::_Any_data &, dfly::DenseSet::DensePtr *&&) (__functor=...,
    __args#0=<optimized out>) at /usr/include/c++/9/bits/std_function.h:300
#14 0x0000555555a47970 in std::function<void (dfly::DenseSet::DensePtr*)>::operator()(dfly::DenseSet::DensePtr*) const (__args#0=<optimized out>, this=0x7fffe8007f50) at /usr/include/c++/9/bits/std_function.h:688
#15 dfly::DenseSet::IteratorBase::TraverseApply(dfly::DenseSet::DensePtr*, std::function<void (dfly::DenseSet::DensePtr*)>) (this=this@entry=0x7fffe8007fb0, ptr=<optimized out>, fun=...) at ../src/core/dense_set.cc:855
#16 0x0000555555a61da0 in dfly::StringMap::iterator::ReallocIfNeeded (this=this@entry=0x7fffe8007fb0, ratio=ratio@entry=0.800000012) at ../src/core/string_map.cc:309
#17 0x0000555555a414ee in dfly::(anonymous namespace)::DefragStrMap2 (ratio=0.800000012, sm=0x339c2401470) at ../src/core/compact_object.cc:157
#18 dfly::(anonymous namespace)::DefragSet (ratio=0.800000012, ptr=0x339c2401470, encoding=<optimized out>) at ../src/core/compact_object.cc:220
```

### PR DESCRIPTION
**Pull request by chakaz**
That'd be a total waste of time and energy, not to mention you'll crash.

Fixes #4167

### CODE REVIEW

**Comment by romange** [comment]
So https://github.com/dragonflydb/dragonfly/issues/3822 has not been completed. I will reopen it.

**Review by romange — APPROVED** [review]

**Comment by romange** [comment]
@adiholden  I am considering releasing v1.25.5 with this.

**Comment by kostasrim** [comment]
:man_facepalming:

**Comment by adiholden** [comment]
> @adiholden I am considering releasing v1.25.5 with this.

lets do that

**Pull request merged**
