### PR TITLE
fix(memcached): Register memcached listener to handle `--maxclients`

### LINKED ISSUE #2986: `--maxclients` doesn't apply to memcached port
### Discussed in https://github.com/dragonflydb/dragonfly/discussions/2978

<div type='discussions-op-text'>

<sup>Originally posted by **badraxas** April 30, 2024</sup>
Hi, is this parameter compatible with memcached?

I'm trying to set this parameter to 1, but I can still open as many connections as I want:
```yaml
  memcached:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: --memcached_port=11211 --cluster_mode=emulated --maxclients=1
    ports:
      - "11211:11211"
    networks:
      - network
```</div>

### PR DESCRIPTION
**Pull request by chakaz**
We add other listeners to `listeners`, but we seem to have forgotten to do that to the memcached listener.

Fixes #2986

### CODE REVIEW

**Comment by romange** [comment]
@chakaz  I suggest checking first if other commands that access listeners array continue working with this change. I mean - "client ..." commands, maybe ACL commands etc.

**Comment by kostasrim** [comment]
@chakaz Can you plz add a member variable that distinguishes if a connection is running on memcached port?

The reason is this code in `acl_family.cc`

```
  void AclFamily::Strea instance-method IsHttp      ons(const std::string& user, uint32_t update_cat,
                                                        const Commands& update_commands,
                        → bool                          const AclKeys& update_keys) {
    auto update_cb = [&                              util::Connection* conn) {
      DCHECK(conn);     // In Connection            
      auto connection = public: bool IsHttp() const on*>(conn);
      if (!connection->IsHttp() && connection->cntx()) {
        connection->SendAclUpdateAsync(
            facade::Connection::AclUpdateMessage{user, update_cat, update_commands, update_keys});
      }   
    };  
  
    if (main_listener_) {
      main_listener_->TraverseConnections(update_cb);
    }
  }
```

Ideally we would like to skip those, i,e, `!connection->IsMC`

**Comment by romange** [comment]
@kostasrim  it's per listener attribute so you can check for listener protocol - reids or memcache

**Comment by chakaz** [comment]
> @chakaz I suggest checking first if other commands that access listeners array continue working with this change. I mean - "client ..." commands, maybe ACL commands etc.

I checked with `CLIENT PAUSE`, `CLIENT KILL`, `CLIENT LIST`, `MONITOR`.

Per @kostasrim 's request I also added a check that the protocol is `REDIS`.

Any other checks any of you think I should run?

**Comment by romange** [comment]
Nope, sounds good!

**Review by kostasrim — APPROVED** [review]

**Pull request merged**
