### PR TITLE
fix(server): service exit on rdb load fail

### PR DESCRIPTION
**Pull request by adiholden**
Now if rdb load fails we the server will exit

### CODE REVIEW

**Comment by royjacobson** [comment]
Is this intended for the initial load off of `--dbfilename`? There's also `DEBUG LOAD` where `exit(1)` makes less sense, but maybe it's a debug command so it doesn't matter too much

**Comment by romange** [comment]
How Redis behave in this situation?

**Comment by adiholden** [comment]
> How Redis behave in this situation?

Redis exits if rdb load fails. Btw Redis does not enforces memory limit when the loading the rdb file i.e you can get to 500mb memory after loading the rdb while your max memory is 300mb and load will be successful.

**Comment by adiholden** [comment]
> Is this intended for the initial load off of `--dbfilename`? There's also `DEBUG LOAD` where `exit(1)` makes less sense, but maybe it's a debug command so it doesn't matter too much

yes this intended for the initial load of rdb file

**Review by romange — APPROVED** [review]

**Pull request merged**
