### PR TITLE
docs: add a chinese language readme

### PR DESCRIPTION
**Pull request by Lambert-Rao**
I translate the README doc to a Chinese version
hope it can help more people using Dragonfly project

### CODE REVIEW

**Comment by romange** [comment]
Cool, thanks! Can you please add a link from the main README to this one?

**Review by Lambert-Rao — COMMENTED** [review]
add a link from main readme to chinese readme

**Review by romange — APPROVED** [review]

**Comment by Lambert-Rao** [comment]
I'm new in GitHub, it feels cool to cooperate from internet, though all I can do is only a translate

**Comment by romange** [comment]
Welcome to DragonflyDB community! :)

**Pull request merged**
